#ifndef __SubGUIClass__
#define __SubGUIClass__

/**
@file
Subclass of GUIClass, which is generated by wxFormBuilder.
*/

#include "GUIClass.h"

//// end generated include

/** Implementing GUIClass */
class SubGUIClass : public GUIClass
{
	public:
		/** Constructor */
		SubGUIClass( wxWindow* parent );
	//// end generated class members
	void SubGUIClass::OnExitMenuSelect(wxCommandEvent& event);
	void SubGUIClass::OnButtonClicked(wxCommandEvent& event);
	void SubGUIClass::OnResetMenuSelect(wxCommandEvent& event);
	void SubGUIClass::StatusBarMessage(wxActivateEvent& event);
	void SubGUIClass::reset();
	bool SubGUIClass::CheckWinConditions();
	bool SubGUIClass::CheckTieCondition();

};

#endif // __SubGUIClass__
